<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>hr_sat.Application</RootNamespace>
    <AssemblyName>hr-sat.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\hr-sat.Domain\hr-sat.Domain.csproj" />
    <InternalsVisibleTo Include="hr-sat.Web.Api" />
    <InternalsVisibleTo Include="hr-sat.Tests" />
  </ItemGroup>

</Project>