// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using hr_sat.Infrastructure;

#nullable disable

namespace hr_sat.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260910070000_Add_Candidate_Promotion_Provenance")]
partial class Add_Candidate_Promotion_Provenance
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        AppDbContextModelSnapshot.BuildSnapshotModel(modelBuilder);
    }
}