// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hr_sat.Infrastructure;

#nullable disable

namespace hr_sat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921123643_Add_Smtp_Sign_In_Method_And_Grant")]
    partial class Add_Smtp_Sign_In_Method_And_Grant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hr_sat.Application.Abstractions.Data.PendingFileDeletion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .HasDatabaseName("pending_file_deletion_storage_key_idx");

                    b.ToTable("pending_file_deletion", null, t =>
                        {
                            t.HasCheckConstraint("pending_file_deletion_storage_key_check", "btrim(storage_key) <> ''");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactEmailProvenance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("contact_email_provenance");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("ContactPhoneProvenance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("contact_phone_provenance");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameProvenance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("full_name_provenance");

                    b.Property<string>("HireOutcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("hire_outcome");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IntakeRoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("intake_round_id");

                    b.Property<string>("IntakeSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("email")
                        .HasColumnName("intake_source");

                    b.Property<bool>("IsResubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resubmitted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<int?>("PromotedFromRoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("promoted_from_round_number");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("new")
                        .HasColumnName("review_status");

                    b.Property<bool>("ScreenedOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("screened_out");

                    b.Property<string>("ScreeningVerdict")
                        .HasColumnType("jsonb")
                        .HasColumnName("screening_verdict");

                    b.Property<string>("SourceBodyText")
                        .HasColumnType("text")
                        .HasColumnName("source_body_text");

                    b.Property<string>("SourceOriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("source_original_filename");

                    b.Property<string>("SourceSenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("source_sender_email");

                    b.Property<string>("SourceSenderName")
                        .HasColumnType("text")
                        .HasColumnName("source_sender_name");

                    b.Property<DateTimeOffset?>("SourceSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_sent_at");

                    b.Property<byte[]>("SourceSha256")
                        .HasColumnType("bytea")
                        .HasColumnName("source_sha256");

                    b.Property<long?>("SourceSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("source_size_bytes");

                    b.Property<string>("SourceStorageKey")
                        .HasColumnType("text")
                        .HasColumnName("source_storage_key");

                    b.Property<string>("SourceSubject")
                        .HasColumnType("text")
                        .HasColumnName("source_subject");

                    b.HasKey("Id");

                    b.HasIndex("SourceStorageKey")
                        .IsUnique()
                        .HasDatabaseName("candidate_source_storage_key_key")
                        .HasFilter("source_storage_key IS NOT NULL");

                    b.HasIndex("IntakeRoundId", "SourceSha256")
                        .IsUnique()
                        .HasDatabaseName("candidate_round_source_sha256_key");

                    b.HasIndex("IntakeRoundId", "ImportedAt", "Id")
                        .HasDatabaseName("candidate_round_imported_idx");

                    b.ToTable("candidate", null, t =>
                        {
                            t.HasCheckConstraint("candidate_contact_email_check", "contact_email IS NULL OR char_length(btrim(contact_email)) BETWEEN 1 AND 320");

                            t.HasCheckConstraint("candidate_contact_email_provenance_check", "contact_email_provenance IN ('none', 'formprefilled', 'typed')");

                            t.HasCheckConstraint("candidate_contact_phone_check", "contact_phone IS NULL OR char_length(btrim(contact_phone)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("candidate_contact_phone_provenance_check", "contact_phone_provenance IN ('none', 'formprefilled', 'typed')");

                            t.HasCheckConstraint("candidate_extraction_status_check", "extraction_status IN ('pending', 'succeeded', 'failed')");

                            t.HasCheckConstraint("candidate_full_name_check", "full_name IS NULL OR char_length(btrim(full_name)) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("candidate_full_name_provenance_check", "full_name_provenance IN ('none', 'formprefilled', 'typed')");

                            t.HasCheckConstraint("candidate_hire_outcome_check", "hire_outcome IN ('none', 'hired', 'runaway', 'declined')");

                            t.HasCheckConstraint("candidate_intake_source_check", "intake_source IN ('email', 'form')");

                            t.HasCheckConstraint("candidate_review_status_check", "review_status IN ('new', 'flagged', 'shortlisted', 'rejected')");

                            t.HasCheckConstraint("candidate_source_original_filename_check", "intake_source = 'form' OR (source_original_filename IS NOT NULL AND btrim(source_original_filename) <> '')");

                            t.HasCheckConstraint("candidate_source_sender_email_check", "source_sender_email IS NULL OR char_length(btrim(source_sender_email)) BETWEEN 1 AND 320");

                            t.HasCheckConstraint("candidate_source_sender_name_check", "source_sender_name IS NULL OR char_length(btrim(source_sender_name)) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("candidate_source_sha256_check", "intake_source = 'form' OR (source_sha256 IS NOT NULL AND octet_length(source_sha256) = 32)");

                            t.HasCheckConstraint("candidate_source_size_bytes_check", "intake_source = 'form' OR (source_size_bytes IS NOT NULL AND source_size_bytes > 0)");

                            t.HasCheckConstraint("candidate_source_storage_key_check", "intake_source = 'form' OR (source_storage_key IS NOT NULL AND btrim(source_storage_key) <> '')");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CandidateRequirementReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<long>("VacancyRequirementId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_requirement_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyRequirementId");

                    b.HasIndex("CandidateId", "VacancyRequirementId")
                        .IsUnique()
                        .HasDatabaseName("candidate_requirement_review_candidate_requirement_key");

                    b.ToTable("candidate_requirement_review", null, t =>
                        {
                            t.HasCheckConstraint("candidate_requirement_review_candidate_id_check", "candidate_id > 0");

                            t.HasCheckConstraint("candidate_requirement_review_requirement_id_check", "vacancy_requirement_id > 0");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CvDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("cv_document_candidate_primary_idx")
                        .HasFilter("is_primary");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("cv_document_storage_key_key");

                    b.HasIndex("CandidateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("cv_document_candidate_position_key");

                    b.ToTable("cv_document", null, t =>
                        {
                            t.HasCheckConstraint("cv_document_original_filename_check", "btrim(original_filename) <> ''");

                            t.HasCheckConstraint("cv_document_position_check", "position >= 1");

                            t.HasCheckConstraint("cv_document_sha256_check", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("cv_document_size_bytes_check", "size_bytes > 0");

                            t.HasCheckConstraint("cv_document_storage_key_check", "btrim(storage_key) <> ''");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.FormResponses.CandidateFormResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Cells")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cells");

                    b.Property<DateTimeOffset?>("FormTimestampParsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("form_timestamp_parsed");

                    b.Property<string>("FormTimestampRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_timestamp_raw");

                    b.Property<string>("IdentityKey")
                        .HasColumnType("text")
                        .HasColumnName("identity_key");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("candidate_form_response_current_key")
                        .HasFilter("is_current");

                    b.HasIndex("IdentityKey")
                        .HasDatabaseName("candidate_form_response_identity_idx")
                        .HasFilter("identity_key IS NOT NULL");

                    b.ToTable("candidate_form_response", null, t =>
                        {
                            t.HasCheckConstraint("candidate_form_response_candidate_id_check", "candidate_id > 0");

                            t.HasCheckConstraint("candidate_form_response_cells_check", "jsonb_array_length(cells) > 0");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Dispatches.Dispatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id");

                    b.Property<long>("DispatchRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispatch_run_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<string>("RenderedBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_body");

                    b.Property<string>("RenderedSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_subject");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_kind");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("dispatch_candidate_sent_key")
                        .HasFilter("status = 'sent'");

                    b.HasIndex("DispatchRunId");

                    b.ToTable("dispatch", null, t =>
                        {
                            t.HasCheckConstraint("dispatch_status_check", "status IN ('sent', 'failed')");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Dispatches.DispatchRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("IntakeRoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("intake_round_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("IntakeRoundId")
                        .HasDatabaseName("ix_dispatch_run_intake_round_id");

                    b.HasIndex("VacancyId");

                    b.ToTable("dispatch_run", (string)null);
                });

            modelBuilder.Entity("hr_sat.Domain.EmailTemplates.EmailTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("email_template_vacancy_kind_key");

                    b.ToTable("email_template", null, t =>
                        {
                            t.HasCheckConstraint("email_template_body_check", "btrim(body) <> ''");

                            t.HasCheckConstraint("email_template_kind_check", "kind IN ('shortlisted', 'rejected')");

                            t.HasCheckConstraint("email_template_subject_check", "char_length(btrim(subject)) BETWEEN 1 AND 998");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.IntakeRounds.IntakeRound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId")
                        .IsUnique()
                        .HasDatabaseName("intake_round_vacancy_active_key")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("VacancyId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("intake_round_vacancy_number_key");

                    b.ToTable("intake_round", null, t =>
                        {
                            t.HasCheckConstraint("intake_round_name_check", "name IS NULL OR char_length(btrim(name)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("intake_round_number_check", "round_number >= 1");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.FormLayouts.FormLayout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Columns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("columns");

                    b.Property<string>("HeaderSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("header_snapshot");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId")
                        .IsUnique()
                        .HasDatabaseName("form_layout_vacancy_key");

                    b.ToTable("form_layout", null, t =>
                        {
                            t.HasCheckConstraint("form_layout_header_snapshot_check", "jsonb_array_length(header_snapshot) > 0");

                            t.HasCheckConstraint("form_layout_vacancy_id_check", "vacancy_id > 0");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.ScreeningRuleSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId")
                        .IsUnique()
                        .HasDatabaseName("screening_rule_set_vacancy_key");

                    b.ToTable("screening_rule_set", null, t =>
                        {
                            t.HasCheckConstraint("screening_rule_set_vacancy_id_check", "vacancy_id > 0");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("NeededHires")
                        .HasColumnType("integer")
                        .HasColumnName("needed_hires");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("vacancy", null, t =>
                        {
                            t.HasCheckConstraint("vacancy_closed_at_check", "(status = 'open' AND closed_at IS NULL) OR (status = 'closed' AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("vacancy_needed_hires_check", "needed_hires IS NULL OR needed_hires BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("vacancy_status_check", "status IN ('open', 'closed')");

                            t.HasCheckConstraint("vacancy_title_check", "char_length(btrim(title)) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.VacancyRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phrase");

                    b.Property<string>("PhraseNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("phrase_normalized")
                        .HasComputedColumnSql("lower(btrim(phrase))", true);

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "PhraseNormalized")
                        .IsUnique()
                        .HasDatabaseName("vacancy_requirement_vacancy_phrase_key");

                    b.HasIndex("VacancyId", "Position")
                        .IsUnique()
                        .HasDatabaseName("vacancy_requirement_vacancy_position_key");

                    b.ToTable("vacancy_requirement", null, t =>
                        {
                            t.HasCheckConstraint("vacancy_requirement_phrase_check", "char_length(btrim(phrase)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("vacancy_requirement_position_check", "position >= 1");
                        });
                });

            modelBuilder.Entity("hr_sat.Infrastructure.Email.SmtpSettingsRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasColumnType("text")
                        .HasColumnName("from_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("ProtectedGrant")
                        .HasColumnType("text")
                        .HasColumnName("protected_grant");

                    b.Property<string>("ProtectedPassword")
                        .HasColumnType("text")
                        .HasColumnName("protected_password");

                    b.Property<string>("SignInMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sign_in_method");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("smtp_settings", null, t =>
                        {
                            t.HasCheckConstraint("smtp_settings_sign_in_method_check", "sign_in_method IN ('app-password', 'microsoft-account')");

                            t.HasCheckConstraint("smtp_settings_singleton_check", "id = 1");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.HasOne("hr_sat.Domain.IntakeRounds.IntakeRound", null)
                        .WithMany("Candidates")
                        .HasForeignKey("IntakeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CandidateRequirementReview", b =>
                {
                    b.HasOne("hr_sat.Domain.Candidates.Candidate", null)
                        .WithMany("RequirementReviews")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hr_sat.Domain.Vacancies.VacancyRequirement", null)
                        .WithMany()
                        .HasForeignKey("VacancyRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CvDocument", b =>
                {
                    b.HasOne("hr_sat.Domain.Candidates.Candidate", null)
                        .WithMany("CvDocuments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.FormResponses.CandidateFormResponse", b =>
                {
                    b.HasOne("hr_sat.Domain.Candidates.Candidate", null)
                        .WithMany("FormResponses")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Dispatches.Dispatch", b =>
                {
                    b.HasOne("hr_sat.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hr_sat.Domain.Dispatches.DispatchRun", null)
                        .WithMany()
                        .HasForeignKey("DispatchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Dispatches.DispatchRun", b =>
                {
                    b.HasOne("hr_sat.Domain.IntakeRounds.IntakeRound", null)
                        .WithMany()
                        .HasForeignKey("IntakeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany()
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.EmailTemplates.EmailTemplate", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany("EmailTemplates")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.IntakeRounds.IntakeRound", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany("Rounds")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.FormLayouts.FormLayout", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithOne("FormLayout")
                        .HasForeignKey("hr_sat.Domain.Vacancies.FormLayouts.FormLayout", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.ScreeningRuleSet", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithOne("ScreeningRuleSet")
                        .HasForeignKey("hr_sat.Domain.Vacancies.ScreeningRuleSet", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.VacancyRequirement", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany("Requirements")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.Navigation("CvDocuments");

                    b.Navigation("FormResponses");

                    b.Navigation("RequirementReviews");
                });

            modelBuilder.Entity("hr_sat.Domain.IntakeRounds.IntakeRound", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.Vacancy", b =>
                {
                    b.Navigation("EmailTemplates");

                    b.Navigation("FormLayout");

                    b.Navigation("Requirements");

                    b.Navigation("Rounds");

                    b.Navigation("ScreeningRuleSet");
                });
#pragma warning restore 612, 618
        }
    }
}
