// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hr_sat.Infrastructure;

#nullable disable

namespace hr_sat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901120000_AddPendingFileDeletion")]
    partial class AddPendingFileDeletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            AppDbContextModelSnapshot.BuildSnapshotModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
