// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hr_sat.Infrastructure;

#nullable disable

namespace hr_sat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("new")
                        .HasColumnName("review_status");

                    b.Property<string>("SourceBodyText")
                        .HasColumnType("text")
                        .HasColumnName("source_body_text");

                    b.Property<string>("SourceOriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_original_filename");

                    b.Property<string>("SourceSenderEmail")
                        .HasColumnType("text")
                        .HasColumnName("source_sender_email");

                    b.Property<string>("SourceSenderName")
                        .HasColumnType("text")
                        .HasColumnName("source_sender_name");

                    b.Property<DateTimeOffset?>("SourceSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_sent_at");

                    b.Property<byte[]>("SourceSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("source_sha256");

                    b.Property<long>("SourceSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("source_size_bytes");

                    b.Property<string>("SourceStorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_storage_key");

                    b.Property<string>("SourceSubject")
                        .HasColumnType("text")
                        .HasColumnName("source_subject");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceStorageKey")
                        .IsUnique()
                        .HasDatabaseName("candidate_source_storage_key_key");

                    b.HasIndex("VacancyId", "SourceSha256")
                        .IsUnique()
                        .HasDatabaseName("candidate_vacancy_source_sha256_key");

                    b.HasIndex("VacancyId", "ImportedAt", "Id")
                        .HasDatabaseName("candidate_vacancy_imported_idx");

                    b.ToTable("candidate", null, t =>
                        {
                            t.HasCheckConstraint("candidate_contact_email_check", "contact_email IS NULL OR char_length(btrim(contact_email)) BETWEEN 1 AND 320");

                            t.HasCheckConstraint("candidate_contact_phone_check", "contact_phone IS NULL OR char_length(btrim(contact_phone)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("candidate_extraction_status_check", "extraction_status IN ('pending', 'succeeded', 'failed')");

                            t.HasCheckConstraint("candidate_full_name_check", "full_name IS NULL OR char_length(btrim(full_name)) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("candidate_review_status_check", "review_status IN ('new', 'flagged', 'shortlisted', 'rejected')");

                            t.HasCheckConstraint("candidate_source_original_filename_check", "btrim(source_original_filename) <> ''");

                            t.HasCheckConstraint("candidate_source_sender_email_check", "source_sender_email IS NULL OR char_length(btrim(source_sender_email)) BETWEEN 1 AND 320");

                            t.HasCheckConstraint("candidate_source_sender_name_check", "source_sender_name IS NULL OR char_length(btrim(source_sender_name)) BETWEEN 1 AND 300");

                            t.HasCheckConstraint("candidate_source_sha256_check", "octet_length(source_sha256) = 32");

                            t.HasCheckConstraint("candidate_source_size_bytes_check", "source_size_bytes > 0");

                            t.HasCheckConstraint("candidate_source_storage_key_check", "btrim(source_storage_key) <> ''");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CvDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("cv_document_candidate_primary_idx")
                        .HasFilter("is_primary");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("cv_document_storage_key_key");

                    b.HasIndex("CandidateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("cv_document_candidate_position_key");

                    b.ToTable("cv_document", null, t =>
                        {
                            t.HasCheckConstraint("cv_document_original_filename_check", "btrim(original_filename) <> ''");

                            t.HasCheckConstraint("cv_document_position_check", "position >= 1");

                            t.HasCheckConstraint("cv_document_sha256_check", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("cv_document_size_bytes_check", "size_bytes > 0");

                            t.HasCheckConstraint("cv_document_storage_key_check", "btrim(storage_key) <> ''");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("vacancy", null, t =>
                        {
                            t.HasCheckConstraint("vacancy_closed_at_check", "(status = 'open' AND closed_at IS NULL) OR (status = 'closed' AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("vacancy_status_check", "status IN ('open', 'closed')");

                            t.HasCheckConstraint("vacancy_title_check", "char_length(btrim(title)) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.VacancyRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phrase");

                    b.Property<string>("PhraseNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("phrase_normalized")
                        .HasComputedColumnSql("lower(btrim(phrase))", true);

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("VacancyId")
                        .HasColumnType("bigint")
                        .HasColumnName("vacancy_id");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId", "PhraseNormalized")
                        .IsUnique()
                        .HasDatabaseName("vacancy_requirement_vacancy_phrase_key");

                    b.HasIndex("VacancyId", "Position")
                        .IsUnique()
                        .HasDatabaseName("vacancy_requirement_vacancy_position_key");

                    b.ToTable("vacancy_requirement", null, t =>
                        {
                            t.HasCheckConstraint("vacancy_requirement_phrase_check", "char_length(btrim(phrase)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("vacancy_requirement_position_check", "position >= 1");
                        });
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany("Candidates")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.CvDocument", b =>
                {
                    b.HasOne("hr_sat.Domain.Candidates.Candidate", null)
                        .WithMany("CvDocuments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.VacancyRequirement", b =>
                {
                    b.HasOne("hr_sat.Domain.Vacancies.Vacancy", null)
                        .WithMany("Requirements")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hr_sat.Domain.Candidates.Candidate", b =>
                {
                    b.Navigation("CvDocuments");
                });

            modelBuilder.Entity("hr_sat.Domain.Vacancies.Vacancy", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
